# Generated by Django 5.0.4 on 2024-04-29 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Category Title')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='Category Parent')),
            ],
        ),
    ]
