# Generated by Django 5.0.4 on 2024-04-29 18:05

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Product Description'),
        ),
    ]
