# Generated by Django 5.0.4 on 2024-05-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productattribute_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.TextField(verbose_name='Attribute Value'),
        ),
    ]
