# Generated by Django 5.0.4 on 2024-05-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_varient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varient',
            name='sku',
            field=models.CharField(max_length=50, verbose_name='Varient SKU'),
        ),
    ]
