# Generated by Django 5.0.4 on 2024-05-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_varient_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='varient',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Varient title'),
            preserve_default=False,
        ),
    ]
