# Generated by Django 5.0.4 on 2024-05-04 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productoption_alter_varient_product_varientoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varientoption',
            name='product',
        ),
        migrations.AddField(
            model_name='varientoption',
            name='varient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.varient', verbose_name='Varient'),
        ),
    ]
