# Generated by Django 5.0.4 on 2024-05-09 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0006_rename_shopping_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(verbose_name='succeeded')),
                ('tracking_id', models.CharField(max_length=150, verbose_name='Payment Gateway Tracking ID')),
                ('status', models.CharField(max_length=150, verbose_name='Order Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order', verbose_name='Order')),
            ],
        ),
    ]
