# Generated by Django 5.0.4 on 2024-05-05 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0015_remove_varientoption_product_varientoption_varient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Unique Identifier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCardLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.shoppingcard', verbose_name='Shopping Card')),
                ('varient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.varient', verbose_name='Varient')),
            ],
        ),
    ]
