# Generated by Django 5.0.4 on 2024-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcard',
            name='is_primary',
            field=models.BooleanField(default=True, verbose_name='Is this your primary shopping card ?'),
        ),
    ]
