# Generated by Django 5.0.4 on 2024-05-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_shopping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='is_primary',
        ),
    ]
