# Generated by Django 5.0.4 on 2024-05-10 17:10

import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_user_alter_orderline_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(django.db.models.functions.datetime.TruncDate('created_at'), models.F('created_at'), name='order_created_at_date_idx'),
        ),
    ]
